# Practical No. 1
## Exploring Deep Learning Libraries and Performing Basic Tensor Operations Using TensorFlow

### Aim
To familiarize students with popular deep learning libraries and perform basic tensor creation and mathematical operations using TensorFlow.

In [1]:
import tensorflow as tf
import numpy as np

print("TensorFlow version:", tf.__version__)
print("NumPy version:", np.__version__)

TensorFlow version: 2.20.0
NumPy version: 2.2.6


In [2]:
!pip install tensorflow


[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import tensorflow as tf

print("TensorFlow is successfully installed.")
print("TensorFlow version:", tf.__version__)

TensorFlow is successfully installed.
TensorFlow version: 2.20.0


In [4]:
scalar = tf.constant(10)

print("Scalar Tensor:")
print(scalar)

Scalar Tensor:
tf.Tensor(10, shape=(), dtype=int32)


In [5]:
matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix Tensor:")
print(matrix)

Matrix Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [6]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

addition = tf.add(a, b)

print("Tensor Addition:")
print(addition)

Tensor Addition:
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [7]:
subtraction = tf.subtract(b, a)

print("Tensor Subtraction:")
print(subtraction)

Tensor Subtraction:
tf.Tensor([3 3 3], shape=(3,), dtype=int32)


In [8]:
multiplication = tf.multiply(a, b)

print("Tensor Multiplication:")
print(multiplication)

Tensor Multiplication:
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [9]:
matrix_a = tf.constant([
    [1, 2],
    [3, 4]
])

matrix_b = tf.constant([
    [5, 6],
    [7, 8]
])

matrix_multiplication = tf.matmul(matrix_a, matrix_b)

print("Matrix Multiplication:")
print(matrix_multiplication)

Matrix Multiplication:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [10]:
tensor = tf.constant([1, 2, 3, 4, 5, 6])

reshaped_tensor = tf.reshape(tensor, (2, 3))

print("Original Tensor:")
print(tensor)

print("\nReshaped Tensor:")
print(reshaped_tensor)

Original Tensor:
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)

Reshaped Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [11]:
numpy_array = np.array([10, 20, 30, 40, 50])

tensorflow_tensor = tf.convert_to_tensor(numpy_array)

print("NumPy Array:")
print(numpy_array)

print("\nTensorFlow Tensor:")
print(tensorflow_tensor)

NumPy Array:
[10 20 30 40 50]

TensorFlow Tensor:
tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int64)


## Comparison of Deep Learning Frameworks

| Feature | TensorFlow | PyTorch | Keras |
|---|---|---|---|
| Developer | Google | Meta | Originally François Chollet / now part of TensorFlow ecosystem |
| Type | Deep Learning Framework | Deep Learning Framework | High-level Deep Learning API |
| Ease of Use | Moderate | Easy to Moderate | Very Easy |
| Computation | Static and Dynamic Graph Support | Dynamic Computation Graph | High-level abstraction |
| Deployment | Excellent | Excellent | Excellent through TensorFlow ecosystem |
| Main Applications | Deep Learning, Production, Computer Vision, NLP | Research, Deep Learning, Computer Vision, NLP | Rapid Model Development and Prototyping |
| GPU Support | Yes | Yes | Yes |
| Community | Very Large | Very Large | Very Large |
| Major Advantage | Production and deployment | Flexibility and research | Simplicity and rapid development |

### TensorFlow
- Developed by Google.
- Suitable for large-scale deep learning applications.
- Provides strong deployment and production capabilities.
- Supports GPU and TPU acceleration.
- Used in computer vision, NLP, recommendation systems, and other AI applications.

### PyTorch
- Developed by Meta.
- Popular in research and experimentation.
- Provides flexible and intuitive tensor operations.
- Supports GPU acceleration.
- Widely used in computer vision, NLP, and research projects.

### Keras
- High-level deep learning API.
- Provides a simple and user-friendly interface.
- Makes neural network development faster.
- Commonly used for education, prototyping, and rapid model development.
- Integrated closely with TensorFlow.

## Conclusion

In this practical, TensorFlow and NumPy were successfully introduced and used for basic tensor operations. Scalar, vector, matrix, and three-dimensional tensors were created. Tensor addition, subtraction, multiplication, matrix multiplication, reshaping, and conversion of NumPy arrays into TensorFlow tensors were performed successfully. TensorFlow, PyTorch, and Keras were also compared based on their features, advantages, and applications.